name: TermHub DB Refresh

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight
  workflow_dispatch:

jobs:
  refresh-db:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          # Consider '3.10' or 'v3.10.0': https://github.com/actions/setup-python/issues/160
          python-version: '3.9.7'

      - name: 'Create env file'
        run: |
          mkdir env
          echo "${{ secrets.ENV_FILE }}" > env/.env

      - name: Create and start virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade wheel
          pip install --upgrade setuptools
          pip install -r requirements.txt

      - name: Refresh db
        run: |
          python backend/db/full_data_refresh.py
